name: awamer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.2
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.4.9
  image_picker: ^1.1.2
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  intl: ^0.20.2
  firebase_messaging: ^15.2.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/App_Logo.jpg
    - assets/images/Delivery.jpg
    - assets/images/Doctors.jpg
    - assets/images/Pharmacies.jpg
    - assets/images/Restaurants.jpg
    - assets/images/Stores.jpg
    - assets/images/parcel.jpg
    - assets/images/Internal.jpg
    - assets/images/Dentist.jpg
    - assets/images/Pediatrics.jpg
    - assets/images/Orthopedic.jpg
    - assets/images/Dermatology.jpg
    - assets/images/Ophthalmology.jpg
    - assets/images/ENT.jpg
    - assets/images/Psychiatry.jpg
    - assets/images/HumanPharmacy.jpg
    - assets/images/VeterinaryPharmacy.jpg
    - assets/images/FastFood.jpg
    - assets/images/TraditionalFood.jpg
    - assets/images/Grocery.jpg

flutter_native_splash:
  color: "#4C9581"
  image: assets/images/App_Logo.jpg
  android: true
  ios: true

  android_12:
    color: "#4C9581"
    image: assets/images/App_Logo.jpg


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/App_Logo.jpg"
  adaptive_icon_background: "#4C9581"
  adaptive_icon_foreground: "assets/images/App_Logo.jpg"